In [4]:
from pathlib import Path
import pandas as pd

# Notebook is inside SRC → go one level up to project root
BASE = Path.cwd().parents[0]

CLEANED = BASE / "Cleaned"

print("Project base:", BASE)
print("Cleaned folder exists:", CLEANED.exists())

Project base: /Users/iftysikder/Desktop/Retail Data
Cleaned folder exists: True

In [5]:
sales = pd.read_csv(CLEANED / "sales_clean.csv", parse_dates=["Date"])
features = pd.read_csv(CLEANED / "features_clean.csv", parse_dates=["Date"])
stores = pd.read_csv(CLEANED / "stores_clean.csv")

print("Sales rows:", len(sales))
print("Features rows:", len(features))
print("Stores rows:", len(stores))

Sales rows: 421570
Features rows: 8190
Stores rows: 45

In [6]:
df = sales.merge(
    features,
    on=["Store_ID", "Date"],
    how="left"
)

print("Rows after sales + features merge:", len(df))

Rows after sales + features merge: 421570

In [7]:
df = df.merge(
    stores,
    on="Store_ID",
    how="left"
)

print("Rows after adding stores:", len(df))

Rows after adding stores: 421570

In [8]:
print("Rows before merge:", len(sales))
print("Rows after merge :", len(df))

if len(df) != len(sales):
    raise ValueError("❌ Row count mismatch after merge!")

print("Missing Store_Type:", df["Store_Type"].isna().sum())
print("Missing Temperature:", df["Temperature"].isna().sum())

Rows before merge: 421570
Rows after merge : 421570
Missing Store_Type: 0
Missing Temperature: 0

In [9]:
df["Is_Return_Week"] = (df["Weekly_Sales"] < 0).astype(int)

df[["Weekly_Sales", "Is_Return_Week"]].head()

   Weekly_Sales  Is_Return_Week
0      24924.50               0
1      46039.49               0
2      41595.55               0
3      19403.54               0
4      21827.90               0

In [10]:
output_path = CLEANED / "retail_analytics.csv"
df.to_csv(output_path, index=False)

print("✅ Step 4 complete")
print("Final dataset saved as:", output_path)
print("Total columns:", len(df.columns))

✅ Step 4 complete
Final dataset saved as: /Users/iftysikder/Desktop/Retail Data/Cleaned/retail_analytics.csv
Total columns: 18

In [11]:
df.head(3)

,Store_ID,Dept_ID,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,Promo_Discount_1,Promo_Discount_2,Promo_Discount_3,Promo_Discount_4,Promo_Discount_5,CPI,Unemployment,IsHoliday_y,Store_Type,Store_Size,Is_Return_Week
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False,A,151315,0
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True,A,151315,0
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False,A,151315,0